# Generated by Django 2.2.5 on 2020-02-25 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework_webServices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='module_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='average_rating',
            field=models.FloatField(default=5, null=True),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='professor_code',
            field=models.ManyToManyField(to='coursework_webServices.Professor'),
        ),
    ]
