# Generated by Django 2.2.5 on 2020-02-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework_webServices', '0002_auto_20200225_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
