# Generated by Django 2.2.5 on 2020-02-26 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework_webServices', '0003_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_semester',
        ),
        migrations.RemoveField(
            model_name='module',
            name='professor_names',
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_semester', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('academic_year', models.IntegerField(default=2020)),
                ('module', models.ManyToManyField(to='coursework_webServices.Module')),
                ('professor_names', models.ManyToManyField(to='coursework_webServices.Professor')),
            ],
        ),
    ]
