# Generated by Django 2.2.5 on 2020-02-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework_webServices', '0004_auto_20200226_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='module',
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coursework_webServices.Module'),
        ),
    ]
