# Generated by Django 2.2.5 on 2020-02-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework_webServices', '0005_auto_20200226_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='module_code',
            field=models.ManyToManyField(to='coursework_webServices.Module'),
        ),
    ]
