# Generated by Django 2.2.5 on 2020-02-28 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework_webServices', '0006_auto_20200228_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='academic_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='rating',
            name='module_semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
    ]
