# Generated by Django 2.2.5 on 2020-02-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework_webServices', '0007_auto_20200228_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='module_code',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='module_semester',
        ),
        migrations.AddField(
            model_name='rating',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coursework_webServices.Module'),
        ),
    ]
