# Generated by Django 2.2.5 on 2020-02-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework_webServices', '0009_auto_20200228_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='professor_code',
        ),
        migrations.AddField(
            model_name='rating',
            name='professor_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coursework_webServices.Professor'),
        ),
    ]
